// SPDX-FileCopyrightText: 2026 UnionTech Software Technology Co., Ltd.
// SPDX-License-Identifier: GPL-3.0-or-later
#ifndef DD_MEME_WALLPAPER_GLOBAL_H
#define DD_MEME_WALLPAPER_GLOBAL_H

#include <dfm-base/dfm_log_defines.h>

#define DD_MEME_WALLPAPER_NAMESPACE ddplugin_meme

#define DD_MEME_WALLPAPER_BEGIN_NAMESPACE namespace DD_MEME_WALLPAPER_NAMESPACE{
#define DD_MEME_WALLPAPER_END_NAMESPACE }
#define DD_MEME_WALLPAPER_USE_NAMESPACE using namespace DD_MEME_WALLPAPER_NAMESPACE;

DD_MEME_WALLPAPER_BEGIN_NAMESPACE
DFM_LOG_USE_CATEGORY(DD_MEME_WALLPAPER_NAMESPACE)
DD_MEME_WALLPAPER_END_NAMESPACE

#endif
